TODOLIST_NAME = 'todo.md'
NOTES_DIRS = ['test_notes']
VALID_EXT = ['.md']
CHECKLIST_CHECKED_MARKERS = ['* [x]'] 
CHECKLIST_UNCHECKED_MARKERS = ['* [ ]'] 
HEX_START = 0
HEX_BITS = 8
PRIORITY_THRESHOLD = 3 
